In [2]:
valid = [450, 800, 630, 740, 950]
invalid = [10, 200, 100, 50, 120]
total = [900, 1000, 1200, 890, 2300]

In [7]:
turnout = []
for i in range(0, len(valid)):
    t = round((valid[i] + invalid[i]) / total[i] * 100, 2)
    turnout.append(t)

In [8]:
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [10]:
list(zip(valid, invalid))

[(450, 10), (800, 200), (630, 100), (740, 50), (950, 120)]

In [11]:
list(zip(valid, invalid, total))

[(450, 10, 900),
 (800, 200, 1000),
 (630, 100, 1200),
 (740, 50, 890),
 (950, 120, 2300)]

In [12]:
turnout = []
for triple in zip(valid, invalid, total):
    t = round((triple[0] + triple[1]) / triple[2] * 100)
    turnout.append(t)
print(turnout)

[51, 100, 61, 89, 47]


In [15]:
a = list(zip(valid, invalid, total))

In [16]:
a[1][0]

800

In [18]:
a, b = 0, 1

In [19]:
print(a)
print(b)

0
1


In [20]:
turnout = []
for v, i, t in zip(valid, invalid, total):
    res = round((v + i) / t * 100, 2)
    turnout.append(res)
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [22]:
turnout = [round((v + i) / t * 100, 2) for v, i, t in zip(valid, invalid, total)]
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [ ]:
!pip install numpy --upgrade

In [23]:
import numpy as np

In [24]:
Valid = np.array(valid)
Invalid = np.array(invalid)
Total = np.array(total)

In [25]:
Valid + Invalid

array([ 460, 1000,  730,  790, 1070])

In [26]:
valid + invalid

[450, 800, 630, 740, 950, 10, 200, 100, 50, 120]

In [27]:
"abv" + "678"

'abv678'

In [31]:
np.round((Valid + Invalid) / Total * 100, 2)

array([ 51.11, 100.  ,  60.83,  88.76,  46.52])

In [34]:
Turnout = ((Valid + Invalid) / Total * 100).round(2)
print(Turnout)

[ 51.11 100.    60.83  88.76  46.52]


In [35]:
numbers = np.array([4, 6, 8, 1, 0])

In [37]:
numbers.dtype

dtype('int64')

In [38]:
decimals = np.array([2.5, 6.8, 9.4, 0])

In [39]:
print(decimals)

[2.5 6.8 9.4 0. ]


In [40]:
decimals.dtype

dtype('float64')

In [41]:
answers = np.array(["yes", "no", "no answer", "yes", "no"])

In [42]:
answers

array(['yes', 'no', 'no answer', 'yes', 'no'], dtype='<U9')

In [43]:
answers.dtype

dtype('<U9')

In [44]:
YN = np.array([True, False, True])

In [45]:
YN.dtype

dtype('bool')

In [47]:
new_numbers = numbers.astype(float)

In [48]:
new_numbers

array([4., 6., 8., 1., 0.])

In [49]:
YN.astype(int)

array([1, 0, 1])

In [50]:
points = np.array([150, 0, 20, 0, 20, 30, 0])

In [51]:
print(points.size)

7


In [53]:
print(points.ndim)

1


In [54]:
points > 0

array([ True, False,  True, False,  True,  True, False])

In [55]:
(points > 0).sum()

4

In [56]:
(points > 10) & (points < 30)

array([False, False,  True, False,  True, False, False])

In [57]:
points > 10 & points < 30

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [59]:
(points < 10) | (points > 100)

array([ True,  True, False,  True, False, False,  True])

In [60]:
points[0]

150

In [61]:
points[2:5]

array([20,  0, 20])

In [62]:
points[points > 0]

array([150,  20,  20,  30])

In [63]:
np.where(points > 0)

(array([0, 2, 4, 5]),)

In [64]:
sample = np.array([46.76, 45.98, 45.82, 44.72, 46.13, 
                 47.99, 44.60, 45.81, 44.91, 44.95])

In [68]:
print("Min:", sample.min())
print("Max:", sample.max())
print("Mean:", sample.mean())

Min: 44.6
Max: 47.99
Mean: 45.76699999999999


In [70]:
print(np.median(sample))
print(np.quantile(sample, 0.25))
print(np.quantile(sample, 0.75))

45.815
44.92
46.0925


In [71]:
print(np.quantile(sample, [0.25, 0.75]))

[44.92   46.0925]


In [73]:
np.arange(0, 1.25, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [74]:
print(np.quantile(sample, np.arange(0, 1.25, 0.25)))

[44.6    44.92   45.815  46.0925 47.99  ]


In [75]:
print(np.quantile(sample, np.arange(0, 1.1, 0.1)))

[44.6   44.708 44.872 44.938 45.466 45.815 45.884 46.025 46.256 46.883
 47.99 ]
