In [1]:
valid = [450, 800, 630, 740, 950]
invalid = [10, 200, 100, 50, 120]
total = [900, 1000, 1200, 890, 2300]

In [3]:
turnout = []
for i in range(0, len(valid)):
    res = round((valid[i] + invalid[i]) / total[i] * 100, 2)
    turnout.append(res)
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [5]:
list(zip(valid, invalid))

[(450, 10), (800, 200), (630, 100), (740, 50), (950, 120)]

In [7]:
m = list(zip(valid, invalid, total))

In [8]:
m

[(450, 10, 900),
 (800, 200, 1000),
 (630, 100, 1200),
 (740, 50, 890),
 (950, 120, 2300)]

In [9]:
m[1][0]

800

In [11]:
turnout = []
for triple in zip(valid, invalid, total):
    res = round((triple[0] + triple[1]) / triple[2] * 100, 2)
    turnout.append(res)
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [12]:
a, b = 0, 1

In [15]:
turnout = []
for v, i, t in zip(valid, invalid, total):
    res = round((v + i) / t * 100, 2)
    turnout.append(res)
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [17]:
turnout = [round((v + i) / t * 100, 2) for v, i, t in zip(valid, invalid, total)] 
print(turnout)

[51.11, 100.0, 60.83, 88.76, 46.52]


In [18]:
!pip install numpy --upgrade

DEPRECATION: celery 4.4.0 has a non-standard dependency specifier pytz>dev. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np

In [20]:
Valid = np.array(valid)
Invalid = np.array(invalid)
Total = np.array(total)

In [21]:
Valid + Invalid

array([ 460, 1000,  730,  790, 1070])

In [22]:
valid + invalid

[450, 800, 630, 740, 950, 10, 200, 100, 50, 120]

In [23]:
"abc" + "789"

'abc789'

In [26]:
np.round((Valid + Invalid) / Total * 100, 2)

array([ 51.11, 100.  ,  60.83,  88.76,  46.52])

In [28]:
((Valid + Invalid) / Total * 100).round(2)

array([ 51.11, 100.  ,  60.83,  88.76,  46.52])

In [29]:
sorted(valid)

[450, 630, 740, 800, 950]

In [30]:
valid.sort()

In [31]:
Turnout = ((Valid + Invalid) / Total * 100).round(2)

In [32]:
print(Turnout)

[ 51.11 100.    60.83  88.76  46.52]


In [33]:
numbers = np.array([5, 7, 8, 0, 6])
print(numbers)

[5 7 8 0 6]


In [34]:
numbers.dtype

dtype('int64')

In [35]:
decimals = np.array([5.6, 9.3, 2, 9.1])

In [36]:
print(decimals)

[5.6 9.3 2.  9.1]


In [37]:
decimals.dtype

dtype('float64')

In [38]:
answers = np.array(["yes", "no", "no answer", "yes"])

In [39]:
answers

array(['yes', 'no', 'no answer', 'yes'], dtype='<U9')

In [40]:
answers.dtype

dtype('<U9')

In [41]:
YN = np.array([True, False, True])
print(YN.dtype)

bool


In [43]:
numbers_new = numbers.astype(float)
print(numbers_new)

[5. 7. 8. 0. 6.]


In [44]:
numbers.astype(str)

array(['5', '7', '8', '0', '6'], dtype='<U21')

In [45]:
YN.astype(int)

array([1, 0, 1])

In [46]:
points = np.array([150, 0, 20, 0, 20, 30, 0])

In [47]:
len(points)

7

In [48]:
points.size

7

In [50]:
len(np.array([[0, 1], [0, 6]]))

2

In [51]:
np.array([[0, 1], [0, 6]]).size

4

In [52]:
np.array([[0, 1], [0, 6]]).ndim

2

In [53]:
np.array([[0, 1], [0, 6]]).shape

(2, 2)

In [54]:
points > 0

array([ True, False,  True, False,  True,  True, False])

In [55]:
(points > 0).sum()

4

In [ ]:
# and, or, ^
# &, |, ^

In [56]:
(points > 10) & (points < 30)

array([False, False,  True, False,  True, False, False])

In [57]:
points > 10 & points < 30

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [58]:
((points > 10) & (points < 30)).sum()

2

In [59]:
10 < points < 30

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [60]:
((points < 10) | (points > 100)).sum()

4

In [61]:
((points < 10) ^ (points > 100)).sum()

4

In [62]:
points[0]

150

In [64]:
points[2:4]

array([20,  0])

In [65]:
points[(points < 10) | (points > 100)]

array([150,   0,   0,   0])

In [66]:
np.where(points == 0)

(array([1, 3, 6]),)

In [67]:
np.where(points > 0)

(array([0, 2, 4, 5]),)

In [68]:
np.where((points < 10) | (points > 100))

(array([0, 1, 3, 6]),)

In [69]:
sample = np.array([46.76, 45.98, 45.82, 44.72, 46.13, 
                 47.99, 44.60, 45.81, 44.91, 44.95])

In [70]:
print(sample.min())
print(sample.max())
print(sample.mean())

44.6
47.99
45.76699999999999


In [71]:
print(sample.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [73]:
print(np.median(sample))
print(np.quantile(sample, 0.25))
print(np.quantile(sample, 0.75))

45.815
44.92
46.0925


In [74]:
print(np.quantile(sample, [0.25, 0.75]))

[44.92   46.0925]


In [76]:
np.arange(0, 1.25, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
print(np.quantile(sample, np.arange(0, 1.25, 0.25)))

[44.6    44.92   45.815  46.0925 47.99  ]


In [78]:
print(np.quantile(sample, np.arange(0, 1.1, 0.1)))

[44.6   44.708 44.872 44.938 45.466 45.815 45.884 46.025 46.256 46.883
 47.99 ]


In [79]:
help(np.quantile)

Help on function quantile in module numpy:

quantile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
    Compute the q-th quantile of the data along the specified axis.
    
    .. versionadded:: 1.15.0
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Quantile or sequence of quantiles to compute, which must be between
        0 and 1 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the quantiles are computed. The
        default is to compute the quantile(s) along a flattened
        version of the array.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
        If True, then allow t