# Анализ данных в Python

*Алла Тамбовцева*

## Лабораторная работа 2

### Правила игры

За разные задачи можно получить разное число баллов. Чтобы получить оценку 10, нужно предложить корректное решение всех задач.

Задача считается решенной, если код успешно проходит тесты и не содержит грубых нарушений («подгонка» под тесты, копирование кода другого студента). «Подгонка» под тесты – написание кода не для общего случая, а для соответствия конкретным значениям в ячейке с тестами. Пример: пишем не универсальный код для проверки четности числа, а код, который правильно работает только на числах 2, 5, 8, потому что именно эти числа используются в тестах.

### Формат сдачи

Для сдачи домашнего задания необходимо скачать текущий ipynb-файл, вписать в него свои решения, сохранить изменения и загрузить обновленный файл на Dropbox по предложенной на странице курса ссылке. Иметь аккаунт Dropbox для этого не требуется, достаточно пройти по ссылке и выбрать файл на компьютере. Получить ipynb-файл можно, выбрав в Jupyter пункт меню *File → Download as... → Notebook (.ipynb)*.

### Формат выполнения заданий

Во всех задачах для удобства проверки кода требуется написать функцию. Шаблон для функции уже написан, не меняйте её название. В лабораторной работе есть два типа задач:

* Если в задаче нужно написать функцию, которая принимает на вход **готовые объекты** и **возвращает** некоторый результат, впишите свой код вместо `### YOUR CODE HERE` и укажите название переменной с полученным результатом после `return`. Эти задачи по типу аналогичны заданиям первой лабораторной работы, для тестирования решений задач этого типа используются конструкции с `assert`.

* Если в задаче нужно написать функцию, которая запрашивает **данные с клавиатуры** и **выводит результат на экран**, впишите свой код вместо `### YOUR CODE HERE` и не добавляйте к функции `return`. Функция без `return`, но с `print()` в Python возвращает пустое значение типа `None` и просто печатает результат на экране. Пример выполнения и оформления решения – см. задачу 0. 

Для тестирования задач с вводом данных с клавиатуры (а это непростая задача, поскольку нужно имитировать ввод данных и забирать результат из `print()`, который сам по себе ничего не сохраняет) в этом файле создана «фабрика» тестов – класс `Tester()`. Для активации тестов запустите ячейку ниже.

### Активировать тесты для задач с вводом данных

*Автор тестера – Щуров.И.В.*

In [ ]:
# Фабрика тестов для проверки программ, принимающих данные через input()

from collections import deque

class Tester(object):
    def __init__(self, inp):
        self.outputs = []
        self.inputs = deque(inp)
    def print(self, *args, sep = " ", end = "\n"):
        text = sep.join(map(str, args)) + end
        newlines = text.splitlines(keepends=True)
        if self.outputs and self.outputs[-1] and self.outputs[-1][-1] != "\n" and newlines:
            self.outputs[-1] += newlines[0]
            self.outputs.extend(newlines[1:])
        else:
            self.outputs.extend(newlines)
            
    def input(self, *args):
        assert self.inputs, "Вы пытаетесь считать больше элементов, чем предусмотрено условием"
        return self.inputs.popleft()
    def __enter__(self):
        global print
        global input
        print = self.print
        input = self.input
        return self.outputs
    def __exit__(self, *args):
        global print
        global input
        del print
        del input

### Задача 0. Nel mezzo del cammin di nostra vita (решена, не оценивается)

Напишите программу, которая спрашивает у пользователя, в каком круге Ада, если верить «Божественной комедии» Данте, находится Платон, и:

* если ответ верный (`лимб`), выводит на экран сообщение «Молодец!»;
* если ответ неверный (все остальные значения), выводит на экран сообщение «Неверно, перечитайте Данте!».

In [ ]:
def dante():
    
    # YOUR CODE HERE
    
    answer = input("В каком круге Ада находится Платон? ")
    if answer == "лимб":
        print("Молодец!")
    else:
        print("Неверно, перечитайте Данте!")

In [ ]:
dante()

In [ ]:
test_data = [
    ("2", "Неверно, перечитайте Данте!"),
    ("лимб", "Молодец!"), 
    ("3", "Неверно, перечитайте Данте!"),
    ("второй", "Неверно, перечитайте Данте!")
]

for inp, out in test_data:
    with Tester([inp]) as t:
        dante()
        assert len(t) == 1, "Вам нужно вывести ровно одну строку с ответом"
        assert t[0] == out+"\n", "Неверный ответ, была введена строка " + inp

### Задача 1. Filter out (1 балл)

Дан готовый массив целых чисел `data`. Напишите программу, которая запрашивает с клавиатуры два значения $a$ и $b$ (один ввод – одно число, гарантируется, что $b$ не менее $a$) и затем выводит на экран через пробел элементы `data`, которые больше $a$ и меньше $b$, отсортированные по возрастанию.

**Примеры работы программы**

Ввод:

    3
    10

Вывод:

    4 4 4 6 6 6 8 9 9 9
    
Ввод:

    40
    55

Вывод:

    41 43 45 45 45 45 45 46 46 47 48 48 48 48 49

In [ ]:
import numpy as np

def get_values():
    
    data = np.array([38, 17, 36, 11, 29, 19, 46, 25, 10, 21, 
                     6, 25, 43, 9, 18, 10, 2, 25, 33, 25, 4, 
                     18, 15, 40, 4, 20, 33, 46, 34, 35, 18, 
                     24, 45, 48, 8, 45, 39, 1, 3, 23, 26, 11, 
                     31, 6, 12, 25, 48, 2, 20, 9, 39, 12, 37, 
                     45, 4, 22, 47, 21, 41, 48, 6, 15, 45, 45, 
                     30, 35, 36, 2, 48, 49, 23, 3, 40, 27, 9, 
                     13, 1, 38, 24, 11])
    
    ### YOUR CODE HERE
    

In [ ]:
get_values()

In [ ]:
test_data = [
    ("40 55", "41 43 45 45 45 45 45 46 46 47 48 48 48 48 49"),
    ("2 5", "3 3 4 4 4"),
    ("10 34", "11 11 11 12 12 13 15 15 17 18 18 18 19 20 20 21 21 22 23 23 24 24 25 25 25 25 25 26 27 29 30 31 33 33"),
    ("13 16", "15 15"),
    ("12 12", ""),
    ("55 68", ""),
    ("23 32", "24 24 25 25 25 25 25 26 27 29 30 31")
]

for inp, out in test_data:
    with Tester(inp.split()) as t:
        get_values()
        assert len(t) == 1, "Вам нужно вывести ровно одну строку с ответом"
        assert t[0] == out+"\n", "Неверный ответ, была введена строка " + inp

### Задача 2. We are the champions... (1 балл)

В массиве `teams` сохранены уникальные названия команд, участвующих в кейс-чемпионате. В массивах `first` и `second` – баллы, полученные ими в первом и втором туре чемпионата соответственно (порядок элементов соответствует порядку названий в `teams`).

Напишите функцию `get_champion()`, которая принимает на вход **массивы** `teams`, `first`, `second` и возвращает **список** победителей, то есть список команд, набравших максимальное число баллов в сумме за два тура, отсортированный по алфавиту. Считайте, что если несколько команд набрали максимальный балл, все они считаются победителями.

**Примеры работы программы**

На входе:

    np.array(['Три в одном', 'Shooting star', 'The Economist', 'Vita activa', 'Коржики']),
    np.array([30, 20, 0, 10, 40]),
    np.array([15, 10, 15, 40, 5])
    

На выходе:

    ['Vita activa']
    
На входе:

    np.array(['Три в одном', 'Shooting star', 'The Economist', 'Vita activa', 'Коржики']),
    np.array([30, 20, 5, 20, 40]),
    np.array([10, 10, 15, 40, 20])

На выходе:

    ['Vita activa', 'Коржики']

In [ ]:
def get_champion(teams, first, second):
    
    ### YOUR CODE HERE

    return 

In [ ]:
t1, f1, s1 = np.array(['A', 'B', 'C', 'D', 'E']), np.array([30, 20, 5, 20, 30]), np.array([10, 10, 15, 40, 20])
t2, f2, s2 = np.array(['A', 'B', 'C']), np.array([30, 20, 20]), np.array([10, 0, 20])
t3, f3, s3 = np.array(['A', 'S', 'C', 'E', 'N', 'D']), np.array([10, 0, 10, 15, 5, 20]), np.array([10, 12, 0, 5, 15, 0])

assert get_champion(t1, f1, s1) == ["D"], "Неверно"
assert get_champion(t2, f2, s2) == ['A', 'C'], "Неверно"
assert get_champion(t3, f3, s3) == ['A', 'D', 'E', 'N'], "Неверно"

### Задача 3. Just function (1 балл)

Напишите функцию `get_binary()`,  которая принимает на вход **список** `s` значений пола респондентов, участвующих в опросе, а возвращает **массив** из 0 и 1, где 0 соответствует значению `female`, а 1 – значению `male`.

**Примеры работы программы**

На входе:

    ['female', 'male', 'male', 'female']

На выходе:

    array([0, 1, 1, 0])
    
На входе:

    ['male', 'male', 'male', 'female', 'female']
    
На выходе:

    array([1, 1, 1, 0, 0])
    
На входе:

    ['female', 'female', 'female']
    
На выходе:

    array([0, 0, 0])

In [ ]:
def get_binary(s):
    
    ### YOUR CODE HERE
    
    return

In [ ]:
assert np.array_equal(get_binary(['female', 'female', 'female']), np.array([0, 0, 0])), "Неверно"
assert np.array_equal(get_binary(['male', 'female', 'female']), np.array([1, 0, 0])), "Неверно"
assert np.array_equal(get_binary(['male', 'female', 'male', 'female', 'female', 'male']), 
                      np.array([1, 0, 1, 0, 0, 1])), "Неверно"

### Задача 4. Что такое свобода? (2 балла)

Напишите программу, которая запрашивает с клавиатуры перечень значений индекса Freedom House (методология до 2018 года, значения от 1 до 8) через пробел и выводит на экран список из 0 и 1, где 1 соответствует свободным странам (статус *Free*, значения индекса от 1.0 до 2.5 включительно), и 0 – всем остальным странам. 

**Примеры работы программы**

Ввод:

    2.5 3.0 2.7 3.6 4.8 6.5 1.0 1.5 7.0

Вывод:

    [1, 0, 0, 0, 0, 0, 1, 1, 0]
    
Ввод:

    3.5 3.0 2.7 3.6

Вывод:

    [0, 0, 0, 0]

In [ ]:
def get_freedom():
    
    ### YOUR CODE HERE
    

In [ ]:
get_freedom()

In [ ]:
test_data = [("2.5 3.0 2.7 3.6 4.8 6.5 1.0 1.5 7.0", "[1, 0, 0, 0, 0, 0, 1, 1, 0]"),
             ("3.5 3.0 2.7 3.6", "[0, 0, 0, 0]"),
             ("2.5 7.0", "[1, 0]"),
             ("5", "[0]"), ("1.5", "[1]")
            ]

for inp, out in test_data:
    with Tester([inp]) as t:
        get_freedom()
        assert len(t) == 1, "Вам нужно вывести ровно одну строку с ответом"
        assert t[0] == out+"\n", "Неверный ответ, была введена строка " + inp

### Задача 5. Немного статистики (2 балла)

Напишите программу, которая запрашивает с клавиатуры значения выборки через пробел (целые или дробные числа) и выводит на экран нетипичные значения этой выборки через пробел, отсортированные по возрастанию. Если таковых в выборке нет, на экран выводится сообщение "Нетипичных значений нет". В задаче предполагается работа с выборкой, сохранённой в массив NumPy.

**Напоминание.** Нетипичные или нехарактерные значения (они же выбросы) – те, которые не входят в границы типичных значений. Границы типичных значений определяются так:

$$
[\text{Q}_1 - 1.5 \times \Delta; \text{Q}_3 + 1.5 \times \Delta],
$$

где $\text{Q}_1$ и $\text{Q}_3$ – нижний и верхний квартиль выборки, а $\Delta$ – межквартильный размах.

**Примеры работы программы**

Ввод:

    10 34 23 100 30 25 27 32

Вывод:

    10.0 100.0
    
Ввод:

    46 100 43 47 78
    
Вывод:

    Нетипичных значений нет
    
Ввод:

    

In [ ]:
def get_outliers():
    
    ### YOUR CODE HERE


In [ ]:
get_outliers()

In [ ]:
test_data = [
    ("46 100 43 47 78", "Нетипичных значений нет"),
    ("10 34 23 100 30 25 27 32", "10.0 100.0"), 
    ("-5 6 8 10 12 14 12 11", "-5.0"),
    ("45.42 45.78 46.21 47.99 44.88 44.92", "47.99"),
    ("5 6.8 7 10.5 2", "10.5"),
    ("4.8 1.2 0 3.5 2.3", "Нетипичных значений нет")
    
]

for inp, out in test_data:
    with Tester([inp]) as t:
        get_outliers()
        assert len(t) == 1, "Вам нужно вывести ровно одну строку с ответом"
        assert t[0] == out+"\n", "Неверный ответ, была введена строка " + inp

### Вступление к задаче 6*

В **сетевом анализе** часто возникает необходимость фиксировать связи между людьми на основе их биографической информации. Так, иногда считается, что людей можно считать «связанными», то есть потенциально знакомыми, если они работали или учились вместе в одно и то же время. Данные о связях часто представляют в виде **матрицы смежности**. Это матрица размера $n \times n$, где $n$ – число людей, из 0 и 1, где 1 соответствует наличию связи между людьми, а 0 – её отсутствию. Пример матрицы смежности:

             Валя Вася Толя
    Валя       0   1   0
    Вася       1   0   0
    Толя       0   0   0
    
Это матрица соответствует случаю, если Вася и Валя знакомы друг с другом, при этом «знакомство» человека с самим собой не учитывается.

Для построения такой матрицы на основе реальных биографических данных в виде фрагментов резюме с местами работы/учёбы и соответствующими датами могут потребоваться следующие библиотеки, модули и функции.

1. Преобразовать строку с датой в определённом формате в специальный тип *дата-время* можно с помощью функций из [библиотеки](https://docs.python.org/3/library/datetime.html)`datetime`. Пример конвертации даты, содержащей только месяц и год:

        from datetime import datetime
        print(datetime.strptime('01.2023', '%m.%Y'))
    
        2023-01-01 00:00:00
        
2. Чтобы более эффективно и просто проверить пересечение временных интервалов, можно преобразовать результат в формате *дата-время* в строку типа `str`, а затем воспользоваться возможностями [библиотеки](https://datetimerange.readthedocs.io/en/latest/pages/examples/index.html) `datetimerange`. Для работы эту библиотеку необходимо установить, она не входит в базовый набор библиотек, устанавливаемых вместе с Anaconda. Пример проверки пересечения двух временных интервалов:

        from datetimerange import DateTimeRange
        range1 = DateTimeRange("2023-01-01 00:00:00", "2023-03-01 00:00:00")
        range2 = DateTimeRange("2023-02-25 00:00:00", "2023-04-01 00:00:00")
        range3 = DateTimeRange("2024-01-25 00:00:00", "2024-02-01 00:00:00")
        print(range1.is_intersection(range2))
        print(range1.is_intersection(range3))
        
        True
        False

3. Для нахождения пересечений двух списков с местами работы можно преобразовать списки в множества, это один из базовых типов данных в Python. Пример нахождения пересечения списков:

        A = [2, 7, 9, 0, 5]
        B = [2, 5, 3, 4]
        print(set(A).intersection(set(B)))

        {2, 5}
        
4. Для нахождения всех пар значений некоторого списка с повторениями можно воспользоваться функцией `product()` из модуля `itertools`, для нахождения всех уникальных пар значений можно воспользоваться функцией `combinations()` из этого же модуля. Примеры:

        from itertools import product, combinations
        print(list(product([1, 2, 3], repeat = 2)))
        print(list(combinations([1, 2, 3], r = 2)))
        
        [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
        [(1, 2), (1, 3), (2, 3)]
        
5. Чтобы создать массив заданной размерности, состоящий из нулей, можно воспользоваться функцией `zeros()` из NumPy. Пример создания матрицы 3 на 3 и её заполнения ненулевыми значениями:

        import numpy as np
        E = np.zeros((3, 3))

        for i in range(0, 3):
            for j in range(0, 3):
                if i != j:
                    E[i, j] = 2     
        print(E)
        
        [[0. 2. 2.]
         [2. 0. 2.]
         [2. 2. 0.]]

### Задача 6*.  На пути в сеть (3 балла)

В списке `info` хранится информация о том, где разные сотрудники Вышки работали в разное время. Данные по каждому сотруднику сохранены в кортеже, где на первом месте указано имя, на втором – список списков со следующими элементами:

* место работы (строка);
* должность (строка);
* дата начала работы (строка формата `месяц.год`);
* дата окончания работы (строка формата `месяц.год`, текущий месяц, если по настоящее время).

In [ ]:
info = [
    ("Бычков А.С.", [["НИУ ВШЭ, кафедра высшей математики", "старший преподаватель", "09.2023", "04.2024"]]),
    ("Гончаренко В.М.", [["Финансовый Университет", "доцент", "09.2000", "08.2016"],
                   ["НИУ ВШЭ, кафедра высшей математики", "доцент", "09.2016", "04.2024"]]), 
    ("Мальцев А.М.", [["НИУ ВШЭ, департамент политики и управления", "преподаватель", "09.2020", "04.2024"],
                  ["НИУ ВШЭ, лаборатория качественных и количественных методов анализа политических режимов", 
                   "стажер", "01.2016", "12.2017"]]),
    ("Малютина П.А.", [["НИУ ВШЭ, кафедра высшей математики", "секретарь", "09.2017", "06.2020"]]), 
    ("Порецкова А.А.", [["НИУ ВШЭ, департамент политики и управления", "преподаватель", "09.2014", "08.2021"],
                   ["НИУ ВШЭ, департамент политики и управления", "доцент", "09.2021", "04.2024"]]),
    ("Тамбовцева А.А.", [["НИУ ВШЭ, лаборатория качественных и количественных методов анализа политических режимов", 
                         "стажер-исследователь", "04.2014", "08.2014"], 
                    ["НИУ ВШЭ, кафедра высшей математики", "преподаватель", "09.2016", "08.2017"],
                    ["НИУ ВШЭ, кафедра высшей математики", "ассистент", "09.2017", "08.2022"],
                    ["НИУ ВШЭ, кафедра высшей математики", "преподаватель", "09.2022", "04.2024"]]),
    ("Филимонов Д.А.", [["МФТИ, кафедра высшей математики", "доцент", "09.2011", "04.2024"],
                  ["НИУ ВШЭ, кафедра высшей математики", "доцент", "09.2013", "04.2024",
                  "МИИТ", "кафедра прикладной математики", "09.2010", "09.2013"]])
]

Напишите программу, которая на основе списка `info` создаст **двумерный массив** с матрицей смежности, где значение 1 ставится в случае, если сотрудники работали в одном месте в одно время, значение 0 – иначе. Вид массива для самопроверки:

    [[0. 1. 0. 0. 0. 1. 1.]
     [1. 0. 0. 1. 0. 1. 1.]
     [0. 0. 0. 0. 1. 0. 0.]
     [0. 1. 0. 0. 0. 1. 1.]
     [0. 0. 1. 0. 0. 0. 0.]
     [1. 1. 0. 1. 0. 0. 1.]
     [1. 1. 0. 1. 0. 1. 0.]]

*Необязательный совет.* Для удобства дальнейшей работы вместо `info` можно создать новый список кортежей `info2`, где на первом месте имя сотрудника, а на втором – список списков со следующими элементами: место работы, временной интервал типа `DateTimeRange`, соответствующий периоду работы сотрудника в этом месте. Затем – написать функцию, которая принимает на вход пару записей из `info2` и возвращает значение индикатора пересечений по времени работы двух сотрудников в одном и том же месте (число 0 или 1).

In [ ]:
### YOUR CODE HERE ###

*Названия задач:*

*№2: Queen (News of the World, 1977)*<br>
*№4: Песня о свободе, А.Градский, звучит в фильме «Узник замка Иф».*